# Generated by Django 3.2.3 on 2022-11-09 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('by_user_id', models.CharField(max_length=10)),
                ('for_user_id', models.CharField(max_length=10)),
                ('recipe_id', models.CharField(max_length=10)),
                ('created', models.DateTimeField()),
                ('completed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In Progress')], default='in_progress', max_length=11)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('by_user_id', models.CharField(max_length=10)),
                ('for_user_id', models.CharField(max_length=10)),
                ('recipe_id', models.CharField(max_length=10)),
                ('created', models.DateTimeField()),
                ('completed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In Progress')], default='in_progress', max_length=11)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=32)),
                ('ingredients', models.CharField(max_length=10)),
                ('prep_time', models.IntegerField()),
                ('user_id', models.CharField(max_length=12)),
                ('likes', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=300)),
                ('by_user', models.CharField(max_length=10)),
                ('recipe_id', models.CharField(max_length=10)),
                ('for_user', models.CharField(max_length=10)),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('recipe_id', models.CharField(max_length=12)),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cook', 'Cook'), ('customer', 'Customer')], default='customer', max_length=8)),
                ('likes', models.IntegerField(default=0)),
                ('orders_cooked', models.IntegerField(default=0)),
                ('orders_bought', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
