# Generated by Django 3.2.3 on 2022-11-15 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('by_user', models.CharField(max_length=10)),
                ('for_user', models.CharField(max_length=10)),
                ('recipe', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In Progress')], default='in_progress', max_length=11)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/recipes')),
                ('ingredients', models.CharField(blank=True, max_length=10, null=True)),
                ('prep_time', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=300)),
                ('by_user', models.CharField(max_length=10)),
                ('for_user', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kavapp.recipe')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='kavapp.Tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cook', 'Cook'), ('customer', 'Customer')], default='customer', max_length=8)),
                ('likes', models.IntegerField(default=0)),
                ('orders_cooked', models.IntegerField(default=0)),
                ('orders_bought', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('by_user', models.CharField(max_length=10)),
                ('for_user', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In Progress')], default='in_progress', max_length=11)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kavapp.recipe')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
