# Generated by Django 3.2.3 on 2022-11-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historylog',
            old_name='by_user_id',
            new_name='by_user',
        ),
        migrations.RenameField(
            model_name='historylog',
            old_name='for_user_id',
            new_name='for_user',
        ),
        migrations.RenameField(
            model_name='historylog',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='by_user_id',
            new_name='by_user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='for_user_id',
            new_name='for_user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kavapp.profile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipes'),
        ),
    ]
