# Generated by Django 3.2.3 on 2022-11-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kavapp.recipe'),
        ),
    ]
