# Generated by Django 3.2.16 on 2022-11-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
