# Generated by Django 3.2.16 on 2022-11-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0002_alter_order_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In Progress'), ('canceled', 'Canceled')], default='in_progress', max_length=11),
        ),
    ]
