# Generated by Django 3.2.16 on 2022-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0003_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
