# Generated by Django 3.2.16 on 2022-11-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0003_alter_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kavapp.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='for_user',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
