# Generated by Django 3.2.16 on 2022-11-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0004_auto_20221121_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
    ]
