# Generated by Django 3.2.3 on 2022-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0005_auto_20221109_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
