# Generated by Django 3.2.16 on 2022-11-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0005_remove_recipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kavapp.review'),
        ),
    ]
