# Generated by Django 3.2.16 on 2022-11-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0006_recipe_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kavapp.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('by_user', 'owner')},
        ),
        migrations.DeleteModel(
            name='HistoryLog',
        ),
    ]
