# Generated by Django 3.2.16 on 2022-11-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0006_delete_atag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='kavapp.Recipe'),
        ),
    ]
