# Generated by Django 3.2.3 on 2022-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavapp', '0012_auto_20221111_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
