version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib//postgresql/data # This makes a data file in your workdir
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  kavsite:
    image: kavsite
    build: .
    volumes:
      - ./kavsite:/kavsite
    command: > # add python manage.py makemigrations && maybe.
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db