# Generated by Django 3.2.16 on 2022-11-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221116_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
    ]
